mail-sender:
  mail-config:
    host: smtp.gmail.com
    port: 465
    auth: true
    starttls: true
    
spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id:
            client-secret: 
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp


